import type { CodeReviewFinding } from '@funny/shared';
import { describe, test, expect } from 'vitest';

import { decideReviewEvent, formatReviewBody } from '../agents/reviewer/formatter.js';

function finding(
  overrides: Partial<CodeReviewFinding> & Pick<CodeReviewFinding, 'severity'>,
): CodeReviewFinding {
  return {
    file: 'src/a.ts',
    line: 10,
    category: 'security',
    description: 'Potential issue',
    ...overrides,
  };
}

describe('decideReviewEvent', () => {
  test('approves when there are no findings', () => {
    expect(decideReviewEvent([])).toBe('APPROVE');
  });

  test('requests changes for critical or high severity', () => {
    expect(decideReviewEvent([finding({ severity: 'critical' })])).toBe('REQUEST_CHANGES');
    expect(decideReviewEvent([finding({ severity: 'high' })])).toBe('REQUEST_CHANGES');
  });

  test('comments for medium severity without blockers', () => {
    expect(decideReviewEvent([finding({ severity: 'medium' })])).toBe('COMMENT');
  });

  test('comments for low/suggestion-only findings', () => {
    expect(
      decideReviewEvent([finding({ severity: 'low' }), finding({ severity: 'suggestion' })]),
    ).toBe('COMMENT');
  });
});

describe('formatReviewBody', () => {
  test('renders approval summary when there are no findings', () => {
    const body = formatReviewBody('Looks good overall.', []);

    expect(body).toContain('## ReviewBot');
    expect(body).toContain('Looks good overall.');
    expect(body).toContain('No issues found. ✅');
  });

  test('groups findings by severity with location and suggestion', () => {
    const body = formatReviewBody('Needs work.', [
      finding({
        severity: 'high',
        description: 'Unsafe cast',
        suggestion: 'Use a type guard',
      }),
      finding({
        severity: 'suggestion',
        file: 'README.md',
        line: undefined,
        description: 'Consider adding docs',
      }),
    ]);

    expect(body).toContain('**2 findings:**');
    expect(body).toContain('**high** (security) — `src/a.ts:10`');
    expect(body).toContain('Unsafe cast');
    expect(body).toContain('**Suggestion:** Use a type guard');
    expect(body).toContain('**suggestion** (security) — `README.md`');
    expect(body).toContain('Generated by [funny]');
  });
});
