/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface BranchDetailedInfo {
  name: string;
  isLocal: boolean;
  isRemote: boolean;
}

/**
 * Summary of committed-only changes between `base_branch` and `branch`,
 * computed without touching the working tree. Mirrors the TS-side
 * `getCommittedBranchSummary` shape.
 */
export interface BranchSummaryResult {
  linesAdded: number;
  linesDeleted: number;
  unpushedCommitCount: number;
  unpulledCommitCount: number;
  hasRemoteBranch: boolean;
  isMergedIntoBase: boolean;
}

/**
 * For each path in `paths`, return the subset that is ignored by .gitignore /
 * info/exclude / core.excludesFile. Mirrors `git check-ignore --stdin`.
 *
 * Paths must be repo-relative with `/` separators. Paths that resolve to a
 * file inside an ignored directory are also reported as ignored (gix walks
 * the parent chain when matching).
 */
export declare function checkIgnore(cwd: string, paths: Array<string>): Promise<Array<string>>;

export interface CommitFileEntry {
  path: string;
  status: string;
  additions: number;
  deletions: number;
}

export interface DiffSummaryResult {
  files: Array<FileDiffSummaryItem>;
  total: number;
  truncated: boolean;
}

export interface FileDiffSummaryItem {
  path: string;
  status: string;
  staged: boolean;
  additions: number;
  deletions: number;
}

export declare function getBranchSummary(
  cwd: string,
  baseBranch: string,
  branch: string,
): Promise<BranchSummaryResult>;

export declare function getCommitBody(cwd: string, hash: string): Promise<string>;

export declare function getCommitFileDiff(
  cwd: string,
  hash: string,
  filePath: string,
): Promise<string>;

export declare function getCommitFiles(cwd: string, hash: string): Promise<Array<CommitFileEntry>>;

export declare function getCurrentBranch(cwd: string): Promise<string | null>;

export declare function getDefaultBranch(cwd: string): Promise<string | null>;

export declare function getDiffSummary(
  cwd: string,
  excludePatterns?: Array<string> | undefined | null,
  maxFiles?: number | undefined | null,
): Promise<DiffSummaryResult>;

/** Full-context diff (equivalent to git diff -U99999). Shows all lines of the file. */
export declare function getFullContextFileDiff(
  cwd: string,
  filePath: string,
  staged: boolean,
): Promise<string>;

export declare function getLog(
  cwd: string,
  limit?: number | undefined | null,
): Promise<Array<GitLogEntry>>;

export declare function getRemoteUrl(cwd: string): Promise<string | null>;

export declare function getSingleFileDiff(
  cwd: string,
  filePath: string,
  staged: boolean,
): Promise<string>;

export declare function getStashFileDiff(
  cwd: string,
  stashRef: string,
  filePath: string,
): Promise<string>;

export declare function getStashList(cwd: string): Promise<Array<StashEntry>>;

export declare function getStashShow(cwd: string, stashRef: string): Promise<Array<StashFileEntry>>;

export declare function getStatusSummary(
  worktreeCwd: string,
  baseBranch?: string | undefined | null,
  projectCwd?: string | undefined | null,
): Promise<GitStatusSummary>;

export declare function getUnpushedHashes(cwd: string): Promise<Array<string>>;

export interface GitLogEntry {
  hash: string;
  shortHash: string;
  author: string;
  relativeDate: string;
  message: string;
}

export interface GitStatusSummary {
  dirtyFileCount: number;
  unpushedCommitCount: number;
  unpulledCommitCount: number;
  hasRemoteBranch: boolean;
  isMergedIntoBase: boolean;
  linesAdded: number;
  linesDeleted: number;
}

export declare function listBranches(cwd: string): Promise<Array<string>>;

export declare function listBranchesDetailed(cwd: string): Promise<Array<BranchDetailedInfo>>;

/**
 * List every file in the repo: tracked from the index, plus untracked and
 * (optionally) `.gitignore`-ignored files from a worktree walk. Heavy build
 * directories (`node_modules`, `dist`, `.next`, …) are pruned regardless.
 *
 * Returns repository-relative paths with unix separators, deduplicated.
 */
export declare function listFiles(
  cwd: string,
  options?: ListFilesOptions | undefined | null,
): Promise<Array<string>>;

export interface ListFilesOptions {
  includeIgnored?: boolean;
}

/**
 * List repo-relative paths that have any unmerged (conflict) index entries
 * (stage 1, 2, or 3). Mirrors `git ls-files --unmerged` minus the mode /
 * hash / stage columns — callers only need the paths to drive conflict
 * resolution UI.
 */
export declare function listUnmergedFiles(cwd: string): Promise<Array<string>>;

/** Simple ping function to verify the native module loads correctly. */
export declare function ping(): string;

export declare function resetSoft(cwd: string): Promise<void>;

export interface StashEntry {
  index: string;
  message: string;
  relativeDate: string;
}

export interface StashFileEntry {
  path: string;
  additions: number;
  deletions: number;
}
