#!/usr/bin/env bun
// Fitness function: HTTP boundary validation baseline diff.
//
// Enforces that new Hono JSON request-body reads in server/runtime route files
// are validated with a Zod schema before use. Existing debt is frozen in
// .fitness/boundary-validation-baseline.txt so the check can run on every lint
// without requiring a full route migration first.
//
// Usage:
//   bun run fitness:boundary-validation
//   bun run fitness:boundary-validation:refresh

import assert from 'node:assert/strict';
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, relative } from 'node:path';

const ROOT = join(import.meta.dir, '..', '..');
const BASELINE_PATH = join(ROOT, '.fitness', 'boundary-validation-baseline.txt');
const REFRESH = process.argv.includes('--refresh');
const SELF_TEST = process.argv.includes('--self-test');

const ROUTE_ROOTS = ['packages/server/src/routes', 'packages/runtime/src/routes'];
const SOURCE_EXTENSIONS = new Set(['.ts', '.tsx']);
const LOOKAHEAD_LINES = 8;

interface Violation {
  file: string;
  line: number;
  occurrence: number;
  snippet: string;
  reason: string;
}

interface CheckOptions {
  root: string;
  routeRoots: string[];
  baselinePath: string;
}

function walk(dir: string): string[] {
  if (!existsSync(dir)) return [];
  const entries = readdirSync(dir).sort();
  const files: string[] = [];
  for (const entry of entries) {
    const path = join(dir, entry);
    const stat = statSync(path);
    if (stat.isDirectory()) {
      files.push(...walk(path));
      continue;
    }
    const ext = path.slice(path.lastIndexOf('.'));
    if (SOURCE_EXTENSIONS.has(ext)) files.push(path);
  }
  return files;
}

function normalizeSnippet(line: string): string {
  return line.trim().replace(/\s+/g, ' ');
}

function validationNear(lines: string[], startIndex: number, variableName: string): boolean {
  const window = lines.slice(startIndex, startIndex + LOOKAHEAD_LINES + 1).join('\n');
  const escaped = variableName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const validateCall = new RegExp(
    `\\b(validate|parseRequestBody|parseJsonBody)\\s*\\([^;]*\\b${escaped}\\b`,
    's',
  );
  const safeParseCall = new RegExp(`\\.safeParse\\s*\\([^;]*\\b${escaped}\\b`, 's');
  return validateCall.test(window) || safeParseCall.test(window);
}

function inlineValidated(line: string): boolean {
  return (
    /\b(validate|parseRequestBody|parseJsonBody)\s*\([^;]*\bc\.req\.json\s*\(/.test(line) ||
    /\.safeParse\s*\([^;]*\bc\.req\.json\s*\(/.test(line)
  );
}

function assignmentName(line: string): string | null {
  const match = line.match(/\b(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=/);
  return match?.[1] ?? null;
}

function checkFile(absFile: string, root: string): Violation[] {
  const relFile = relative(root, absFile);
  const lines = readFileSync(absFile, 'utf-8').split('\n');
  const violations: Violation[] = [];
  const occurrenceCounts = new Map<string, number>();

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (!/\bc\.req\.json\s*\(/.test(line)) continue;
    if (inlineValidated(line)) continue;

    const variableName = assignmentName(line);
    if (variableName && validationNear(lines, i, variableName)) continue;

    const snippet = normalizeSnippet(line);
    const reason = variableName
      ? `request JSON assigned to \`${variableName}\` without nearby Zod validation`
      : 'request JSON read without nearby Zod validation';
    const occurrenceKey = `${relFile}\t${snippet}\t${reason}`;
    const occurrence = (occurrenceCounts.get(occurrenceKey) ?? 0) + 1;
    occurrenceCounts.set(occurrenceKey, occurrence);

    violations.push({
      file: relFile,
      line: i + 1,
      occurrence,
      snippet,
      reason,
    });
  }

  return violations;
}

function violationKey(v: Violation): string {
  return `${v.file}\t#${v.occurrence}\t${v.snippet}\t${v.reason}`;
}

function collectViolations(opts: Pick<CheckOptions, 'root' | 'routeRoots'>): Violation[] {
  const files = opts.routeRoots.flatMap((dir) => walk(join(opts.root, dir)));
  return files.flatMap((file) => checkFile(file, opts.root));
}

function loadBaseline(baselinePath: string): Set<string> {
  if (!existsSync(baselinePath)) return new Set();
  return new Set(
    readFileSync(baselinePath, 'utf-8')
      .split('\n')
      .filter((line) => line.trim() && !line.startsWith('#')),
  );
}

function writeBaseline(violations: Violation[], baselinePath: string): void {
  mkdirSync(dirname(baselinePath), { recursive: true });
  const sorted = violations.map(violationKey).sort();
  const header =
    '# boundary validation baseline - generated by `bun run fitness:boundary-validation:refresh`\n' +
    '# Each line: <file>\\t<occurrence>\\t<normalized source line>\\t<reason>\n' +
    '# Scope: Hono `c.req.json()` reads in packages/server/src/routes and packages/runtime/src/routes.\n' +
    `# Last refreshed: ${new Date().toISOString()}\n` +
    `# Total violations: ${sorted.length}\n\n`;
  writeFileSync(baselinePath, header + sorted.join('\n') + '\n');
}

function findNewViolations(violations: Violation[], baseline: Set<string>): Violation[] {
  return violations.filter((v) => !baseline.has(violationKey(v)));
}

function runCheck(opts: CheckOptions): number {
  const violations = collectViolations(opts);

  if (REFRESH) {
    writeBaseline(violations, opts.baselinePath);
    console.log(
      `✓ Boundary validation baseline refreshed: ${violations.length} violation(s) frozen`,
    );
    console.log(`  ${opts.baselinePath}`);
    return 0;
  }

  const baseline = loadBaseline(opts.baselinePath);
  const newViolations = findNewViolations(violations, baseline);

  if (newViolations.length === 0) {
    console.log(
      `✓ No new unvalidated HTTP JSON body reads (baseline: ${baseline.size}, current: ${violations.length})`,
    );
    return 0;
  }

  console.error(`\n✗ ${newViolations.length} new unvalidated HTTP JSON body read(s):\n`);
  for (const violation of newViolations) {
    console.error(`  ${violation.file}:${violation.line}`);
    console.error(`    ${violation.reason}`);
    console.error(`    ${violation.snippet}`);
  }
  console.error(
    '\n  Validate the request body with a Zod schema before using it. If this is intentional debt, refresh the baseline:\n    bun run fitness:boundary-validation:refresh\n',
  );
  return 1;
}

function writeRoute(root: string, name: string, source: string): void {
  const routesDir = join(root, 'packages', 'server', 'src', 'routes');
  mkdirSync(routesDir, { recursive: true });
  writeFileSync(join(routesDir, name), source.trimStart());
}

function runSelfTest(): void {
  const root = mkdtempSync(join(tmpdir(), 'funny-boundary-validation-'));
  try {
    writeRoute(
      root,
      'validated.ts',
      `
      route.post('/validated', async (c) => {
        const raw = await c.req.json();
        const parsed = validate(schema, raw);
        return c.json(parsed.value);
      });
      `,
    );
    writeRoute(
      root,
      'safeparse.ts',
      `
      route.post('/safeparse', async (c) => {
        const raw = await c.req.json();
        const parsed = schema.safeParse(raw);
        return c.json(parsed.data);
      });
      `,
    );
    writeRoute(
      root,
      'inline.ts',
      `
      route.post('/inline', async (c) => {
        const parsed = validate(schema, await c.req.json());
        return c.json(parsed.value);
      });
      `,
    );
    writeRoute(
      root,
      'duplicate.ts',
      `
      route.post('/one', async (c) => {
        const body = await c.req.json();
        return c.json(body);
      });
      route.post('/two', async (c) => {
        const body = await c.req.json();
        return c.json(body);
      });
      `,
    );
    writeRoute(
      root,
      'unvalidated.ts',
      `
      route.post('/unvalidated', async (c) => {
        const body = await c.req.json().catch(() => null);
        return c.json(body);
      });
      `,
    );
    writeRoute(
      root,
      'destructure.ts',
      `
      route.post('/destructure', async (c) => {
        const { content } = await c.req.json();
        return c.json({ content });
      });
      `,
    );

    const opts = {
      root,
      routeRoots: ROUTE_ROOTS,
      baselinePath: join(root, '.fitness', 'boundary-validation-baseline.txt'),
    };
    const violations = collectViolations(opts);
    const keys = violations.map(violationKey).sort();

    assert.equal(violations.length, 4);
    assert(keys.some((key) => key.includes('duplicate.ts\t#1\tconst body = await c.req.json();')));
    assert(keys.some((key) => key.includes('duplicate.ts\t#2\tconst body = await c.req.json();')));
    assert(keys.some((key) => key.includes('unvalidated.ts')));
    assert(keys.some((key) => key.includes('destructure.ts')));
    assert(!keys.some((key) => key.startsWith('packages/server/src/routes/validated.ts\t')));
    assert(!keys.some((key) => key.startsWith('packages/server/src/routes/safeparse.ts\t')));
    assert(!keys.some((key) => key.startsWith('packages/server/src/routes/inline.ts\t')));

    writeBaseline(violations, opts.baselinePath);
    assert.equal(runCheck(opts), 0);

    writeRoute(
      root,
      'new-debt.ts',
      `
      route.post('/new-debt', async (c) => {
        const body = await c.req.json();
        return c.json(body);
      });
      `,
    );
    const newViolations = findNewViolations(
      collectViolations(opts),
      loadBaseline(opts.baselinePath),
    );
    assert.equal(newViolations.length, 1);
    assert.equal(newViolations[0]?.file, 'packages/server/src/routes/new-debt.ts');
    console.log('✓ Boundary validation self-test passed');
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
}

function main(): void {
  if (SELF_TEST) {
    runSelfTest();
    return;
  }

  const exitCode = runCheck({
    root: ROOT,
    routeRoots: ROUTE_ROOTS,
    baselinePath: BASELINE_PATH,
  });
  if (exitCode !== 0) process.exit(exitCode);
}

main();
