#!/usr/bin/env bun
// Fitness function: JSON.parse boundary validation baseline diff.
//
// Freezes existing direct JSON.parse call sites in service/runtime packages.
// New structurally consumed JSON should go through parseStoredJson,
// parseExternalPayload, or a narrowly scoped parser with tests.

import assert from 'node:assert/strict';
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, relative } from 'node:path';

const ROOT = join(import.meta.dir, '..', '..');
const BASELINE_PATH = join(ROOT, '.fitness', 'json-boundary-validation-baseline.txt');
const REFRESH = process.argv.includes('--refresh');
const SELF_TEST = process.argv.includes('--self-test');

const INPUT_ROOTS = [
  'packages/server/src',
  'packages/runtime/src',
  'packages/shared/src',
  'packages/core/src',
  'packages/orchestrator/src',
  'packages/memory/src',
];
const SOURCE_EXTENSIONS = new Set(['.ts', '.tsx', '.mts', '.cts']);
const EXCLUDED_PATTERNS = [
  /(?:^|\/)__tests__(?:\/|$)/,
  /(?:^|\/)test(?:\/|$)/,
  /\.test\.tsx?$/,
  /packages\/shared\/src\/json-validation\.ts$/,
];

interface Violation {
  file: string;
  line: number;
  occurrence: number;
  snippet: string;
  reason: string;
}

interface CheckOptions {
  root: string;
  inputRoots: string[];
  baselinePath: string;
}

function shouldSkip(path: string): boolean {
  return EXCLUDED_PATTERNS.some((pattern) => pattern.test(path));
}

function walk(dir: string, root: string): string[] {
  if (!existsSync(dir)) return [];
  const entries = readdirSync(dir).sort();
  const files: string[] = [];
  for (const entry of entries) {
    const path = join(dir, entry);
    const rel = relative(root, path);
    if (shouldSkip(rel)) continue;
    const stat = statSync(path);
    if (stat.isDirectory()) {
      files.push(...walk(path, root));
      continue;
    }
    const ext = path.slice(path.lastIndexOf('.'));
    if (SOURCE_EXTENSIONS.has(ext)) files.push(path);
  }
  return files;
}

function normalizeSnippet(line: string): string {
  return line.trim().replace(/\s+/g, ' ');
}

function checkFile(absFile: string, root: string): Violation[] {
  const relFile = relative(root, absFile);
  const lines = readFileSync(absFile, 'utf-8').split('\n');
  const violations: Violation[] = [];
  const occurrenceCounts = new Map<string, number>();

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (!/\bJSON\.parse\s*\(/.test(line)) continue;

    const snippet = normalizeSnippet(line);
    const reason = 'direct JSON.parse without boundary parser helper';
    const occurrenceKey = `${relFile}\t${snippet}\t${reason}`;
    const occurrence = (occurrenceCounts.get(occurrenceKey) ?? 0) + 1;
    occurrenceCounts.set(occurrenceKey, occurrence);
    violations.push({ file: relFile, line: i + 1, occurrence, snippet, reason });
  }

  return violations;
}

function violationKey(v: Violation): string {
  return `${v.file}\t#${v.occurrence}\t${v.snippet}\t${v.reason}`;
}

function collectViolations(opts: Pick<CheckOptions, 'root' | 'inputRoots'>): Violation[] {
  const files = opts.inputRoots.flatMap((dir) => walk(join(opts.root, dir), opts.root));
  return files.flatMap((file) => checkFile(file, opts.root));
}

function loadBaseline(baselinePath: string): Set<string> {
  if (!existsSync(baselinePath)) return new Set();
  return new Set(
    readFileSync(baselinePath, 'utf-8')
      .split('\n')
      .filter((line) => line.trim() && !line.startsWith('#')),
  );
}

function writeBaseline(violations: Violation[], baselinePath: string): void {
  mkdirSync(dirname(baselinePath), { recursive: true });
  const sorted = violations.map(violationKey).sort();
  const header =
    '# JSON boundary validation baseline - generated by `bun run fitness:json-validation:refresh`\n' +
    '# Each line: <file>\\t<occurrence>\\t<normalized source line>\\t<reason>\n' +
    '# Scope: direct JSON.parse calls in server/runtime/shared/core/orchestrator/memory source, excluding tests and json-validation helper internals.\n' +
    `# Last refreshed: ${new Date().toISOString()}\n` +
    `# Total violations: ${sorted.length}\n\n`;
  writeFileSync(baselinePath, header + sorted.join('\n') + (sorted.length > 0 ? '\n' : ''));
}

function findNewViolations(violations: Violation[], baseline: Set<string>): Violation[] {
  return violations.filter((v) => !baseline.has(violationKey(v)));
}

function runCheck(opts: CheckOptions): number {
  const violations = collectViolations(opts);

  if (REFRESH) {
    writeBaseline(violations, opts.baselinePath);
    console.log(`✓ JSON validation baseline refreshed: ${violations.length} violation(s) frozen`);
    console.log(`  ${opts.baselinePath}`);
    return 0;
  }

  const baseline = loadBaseline(opts.baselinePath);
  const newViolations = findNewViolations(violations, baseline);
  if (newViolations.length === 0) {
    console.log(
      `✓ No new direct JSON.parse boundary reads (baseline: ${baseline.size}, current: ${violations.length})`,
    );
    return 0;
  }

  console.error(`\n✗ ${newViolations.length} new direct JSON.parse call(s):\n`);
  for (const violation of newViolations) {
    console.error(`  ${violation.file}:${violation.line}`);
    console.error(`    ${violation.reason}`);
    console.error(`    ${violation.snippet}`);
  }
  console.error(
    '\n  Use parseStoredJson(schema, raw) or parseExternalPayload(schema, value). If this is intentional temporary debt, refresh the baseline:\n    bun run fitness:json-validation:refresh\n',
  );
  return 1;
}

function writeSource(root: string, name: string, source: string): void {
  const dir = join(root, 'packages', 'runtime', 'src', 'services');
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, name), source.trimStart());
}

function runSelfTest(): void {
  const root = mkdtempSync(join(tmpdir(), 'funny-json-boundary-validation-'));
  try {
    writeSource(
      root,
      'validated.ts',
      `
      import { parseStoredJson } from '@funny/shared/json-validation';
      const parsed = parseStoredJson(schema, raw, 'settings');
      `,
    );
    writeSource(
      root,
      'debt.ts',
      `
      const parsed = JSON.parse(raw) as Settings;
      const other = JSON.parse(otherRaw);
      `,
    );

    const opts = {
      root,
      inputRoots: INPUT_ROOTS,
      baselinePath: join(root, '.fitness', 'json-boundary-validation-baseline.txt'),
    };
    const violations = collectViolations(opts);
    assert.equal(violations.length, 2);
    assert(violations.every((v) => v.file.endsWith('debt.ts')));

    writeBaseline(violations, opts.baselinePath);
    assert.equal(runCheck(opts), 0);

    writeSource(
      root,
      'new-debt.ts',
      `
      export const value = JSON.parse(raw);
      `,
    );
    const newViolations = findNewViolations(
      collectViolations(opts),
      loadBaseline(opts.baselinePath),
    );
    assert.equal(newViolations.length, 1);
    assert.equal(newViolations[0]?.file, 'packages/runtime/src/services/new-debt.ts');
    console.log('✓ JSON boundary validation self-test passed');
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
}

function main(): void {
  if (SELF_TEST) {
    runSelfTest();
    return;
  }
  process.exitCode = runCheck({ root: ROOT, inputRoots: INPUT_ROOTS, baselinePath: BASELINE_PATH });
}

main();
