#!/usr/bin/env bun
// Fitness function: typecheck baseline diff.
//
// Runs tsc --noEmit against each package and compares the error set against
// a frozen baseline at .fitness/typecheck-baseline.txt. Fails when there
// are NEW errors (i.e. errors present now that weren't in the baseline).
//
// Pre-existing errors stay in the baseline so the build doesn't break
// on day one — but every refactor must NOT add new errors.
//
// Usage:
//   bun run typecheck          # check against baseline (CI / pre-commit)
//   bun run typecheck:refresh  # rewrite baseline from current state
//
// Why: a plain `bun run typecheck` that errors on every pre-existing
// failure is useless because nothing ever runs it. A baseline-diff makes
// the check meaningful AND keeps it green by default.

import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

const ROOT = join(import.meta.dir, '..', '..');
const BASELINE_PATH = join(ROOT, '.fitness', 'typecheck-baseline.txt');

// Each entry runs `bunx tsc --noEmit -p <project>`. Add new packages here
// as their own tsconfig.json gains errors worth gating on.
const PROJECTS = [
  'packages/client/tsconfig.json',
  'packages/runtime/tsconfig.json',
  'packages/server/tsconfig.json',
  'packages/shared/tsconfig.json',
  'packages/agent/tsconfig.json',
  'packages/sdk/tsconfig.json',
  'packages/orchestrator/tsconfig.json',
];

const REFRESH = process.argv.includes('--refresh');

interface NormalizedError {
  /** Project-relative file path (e.g. "packages/client/src/.../foo.ts") */
  file: string;
  /** TS error code (e.g. "TS2304") */
  code: string;
  /** Single-line error message (multiline messages get joined with ' / ') */
  message: string;
}

/**
 * Run tsc for a single project and parse its error lines into normalized
 * (file, code, message) tuples. Line numbers are intentionally dropped —
 * adding a blank line above an existing error shouldn't count as a "new"
 * error.
 */
function runTsc(project: string): NormalizedError[] {
  const result = spawnSync(
    'bunx',
    ['tsc', '--noEmit', '-p', project, '--ignoreDeprecations', '6.0', '--pretty', 'false'],
    { cwd: ROOT, encoding: 'utf-8' },
  );

  // tsc may write to stdout or stderr depending on version
  const output = (result.stdout || '') + (result.stderr || '');
  const lines = output.split('\n');

  const errors: NormalizedError[] = [];
  let current: NormalizedError | null = null;

  for (const line of lines) {
    // Primary error pattern: "path/to/file.ts(123,45): error TS1234: message"
    const match = line.match(/^(.+?)\((\d+),(\d+)\): error (TS\d+): (.*)$/);
    if (match) {
      if (current) errors.push(current);
      const [, file, , , code, message] = match;
      current = { file, code, message };
      continue;
    }

    // Continuation lines (multiline error messages) start with whitespace
    if (current && /^\s+\S/.test(line)) {
      current.message += ' / ' + line.trim();
      continue;
    }

    // Anything else terminates the current error
    if (current) {
      errors.push(current);
      current = null;
    }
  }
  if (current) errors.push(current);

  return errors;
}

/** Stable string key for an error (used to build the baseline set). */
function errorKey(e: NormalizedError): string {
  return `${e.file}\t${e.code}\t${e.message}`;
}

function loadBaseline(): Set<string> {
  if (!existsSync(BASELINE_PATH)) return new Set();
  return new Set(
    readFileSync(BASELINE_PATH, 'utf-8')
      .split('\n')
      .filter((l) => l.trim() && !l.startsWith('#')),
  );
}

function writeBaseline(errors: NormalizedError[]): void {
  mkdirSync(dirname(BASELINE_PATH), { recursive: true });
  const sorted = errors.map(errorKey).sort();
  const header =
    '# typecheck baseline — generated by `bun run typecheck:refresh`\n' +
    '# Each line: <file>\\t<TS code>\\t<message>\n' +
    `# Last refreshed: ${new Date().toISOString()}\n` +
    `# Total errors: ${sorted.length}\n\n`;
  writeFileSync(BASELINE_PATH, header + sorted.join('\n') + '\n');
}

function main(): void {
  console.log('Running tsc against', PROJECTS.length, 'projects…');
  const allErrors: NormalizedError[] = [];
  for (const project of PROJECTS) {
    if (!existsSync(join(ROOT, project))) {
      console.log(`  skipping ${project} (not found)`);
      continue;
    }
    process.stdout.write(`  ${project}… `);
    const errors = runTsc(project);
    console.log(`${errors.length} error(s)`);
    allErrors.push(...errors);
  }

  if (REFRESH) {
    writeBaseline(allErrors);
    console.log(`\n✓ Baseline refreshed: ${allErrors.length} error(s) frozen`);
    console.log(`  ${BASELINE_PATH}`);
    return;
  }

  const baseline = loadBaseline();
  const newErrors = allErrors.filter((e) => !baseline.has(errorKey(e)));

  if (newErrors.length === 0) {
    console.log(
      `\n✓ No new typecheck errors (baseline: ${baseline.size}, current: ${allErrors.length})`,
    );
    return;
  }

  console.error(`\n✗ ${newErrors.length} NEW typecheck error(s) since baseline:\n`);
  for (const e of newErrors) {
    console.error(`  ${e.file}: ${e.code}: ${e.message}`);
  }
  console.error(
    `\n  If these errors are intentional, refresh the baseline:\n    bun run typecheck:refresh\n`,
  );
  process.exit(1);
}

main();
